_format_version: "1.1"

consumers:
  - username: anon
    keyauth:
      - key: ${ANON_KEY}
  - username: service_role
    keyauth:
      - key: ${SERVICE_ROLE_KEY}

acls:
  - consumer: anon
    group: anon
  - consumer: service_role
    group: admin

services:
  - name: auth-v1-open
    url: http://auth:9999/verify
    routes:
      - name: auth-v1-open
        paths:
          - /auth/v1/verify
        strip_path: true
        protocols:
          - http
          - https

  - name: auth-v1
    url: http://auth:9999/
    routes:
      - name: auth-v1
        paths:
          - /auth/v1
        strip_path: true
        protocols:
          - http
          - https

  - name: rest-v1
    url: http://rest:3000/
    routes:
      - name: rest-v1
        paths:
          - /rest/v1
        strip_path: true
        protocols:
          - http
          - https

  - name: realtime-v1
    url: http://realtime:4000/socket/
    routes:
      - name: realtime-v1
        paths:
          - /realtime/v1
        strip_path: true
        protocols:
          - http
          - https

  - name: storage-v1
    url: http://storage:8000/
    routes:
      - name: storage-v1
        paths:
          - /storage/v1
        strip_path: true
        protocols:
          - http
          - https

  - name: pg-meta
    url: http://meta:8080/
    routes:
      - name: pg-meta
        paths:
          - /pg
        strip_path: true
        protocols:
          - http
          - https
    plugins:
      - name: key-auth
        config:
          hide_credentials: false
      - name: acl
        config:
          hide_groups_header: true
          allow:
            - admin

upstreams:
  - name: auth-v1-open
    targets:
      - target: auth:9999
  - name: auth-v1
    targets:
      - target: auth:9999
  - name: rest-v1
    targets:
      - target: rest:3000
  - name: realtime-v1
    targets:
      - target: realtime:4000
  - name: storage-v1
    targets:
      - target: storage:8000
  - name: pg-meta
    targets:
      - target: meta:8080
